cassandra:
  hostname: productCrawler
  image: cassandra:latest
  ports:
    - "9042:9042"

rabbitmq:
  image: rabbitmq:management
  ports:
    - "5672:5672"
    - "15672:15672"

mongodb:
  image: mongo:3.4.4
  ports:
    - "27017:27017"
